### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jmfayard** [lotharschulz/ktorjib#5]
It's nice that have a paragraph `preconditions` but it mixes what the project use and what has to be configured to be able to actually test the project. 

Your project uses Kotlin, Gradle, Jib, ... ok  but I don't have anything to setup, it's done automatically. 

On the other hand, as a user, I have a list of actions to do to try out the project

- Install Java 12, maybe with https://sdkman.io/ ?
- Install skaffold https://skaffold.dev/docs/getting-started/#installing-skaffold
- Install minikube and virtualbox https://kubernetes.io/docs/setup/learning-environment/minikube/
- Install and configure gcloud https://cloud.google.com/sdk/gcloud/?hl=en ? 

Not sure about the last one, but when I tried your project, I had an error

```
> com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException:
> Build image failed, 
> perhaps you should make sure your credentials for 'gcr.io/ktor-jib/kjib-image' are set up correctly. 
> See https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#what-should-i-do-when-the-registry-responds-with-unauthorized for help
```

**Comment by lotharschulz** [comment]
Thanks! (and sorry I answer rather late)

> Your project uses Kotlin, Gradle, Jib, ... ok but I don't have anything to setup, it's done automatically.

Interesting to hear. Please share how it's done automatically.

---
You have a point with regards to [Java 12](https://github.com/lotharschulz/ktorjib/pull/6). skaffold, minikube and virtualbox are listed already (I did not check if those technologies have been added after you provided feedback.

---

No cloud provider is mentioned as a particular cloud provider for a reason: I believe you do not need a cloud provider to reproduce the repository setup. 

I use the _container image repository_ prefix _gcr.io_ in this repository: _[gcr.io/ktor-jib/kjib-image](https://github.com/lotharschulz/ktorjib/search?q=gcr.io%2Fktor-jib%2Fkjib-image)_. That indicates such a container image could be downloaded from [grc.io container registry](https://cloud.google.com/container-registry/). However this is just an indication and not intended. No container registry prefix (indicating [docker hub](https://hub.docker.com/)) or prefixes like [ecr](https://aws.amazon.com/ecr/) or [azurecr](https://azure.microsoft.com/en-us/services/container-registry/) or else could have been used in theory.

Instead I use _[gcr.io/ktor-jib/kjib-image](https://github.com/lotharschulz/ktorjib/search?q=gcr.io%2Fktor-jib%2Fkjib-image)_ as a reference to skaffold examples:
- https://github.com/GoogleContainerTools/skaffold/blob/master/examples/getting-started/skaffold.yaml#L5
- https://github.com/GoogleContainerTools/skaffold/blob/master/examples/getting-started/k8s-pod.yaml#L8 

[Skaffold](https://github.com/GoogleContainerTools/skaffold) is part of [GoogleContainerTools](https://github.com/GoogleContainerTools), so it is not a surprise that [grc.io container registry](https://cloud.google.com/container-registry/) is used.

**Comment by jmfayard** [comment]
> Interesting to hear. Please share how it's done automatically.

I meant that Gradle auto-bootstrap itself with a shell script, and then download the kotlin compiler etc...

The only requirement is to have Java in the right version installed, the best option being IMHO to use sdkman

Thanks for your other infos!
